sudo: required 

services:
  - docker

before_install:
  - docker build -t dshah2012/docker-reactapp -f Dockerfile.dev .

script:
  - docker run dshah2012/docker-reactapp npm run test -- --coverage --watchAll=false
  
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-reactapp"
  env: "DockerReactapp-env"
  bucket_name: "elasticbeanstalk-us-east-2-696227269688"
  bucket_path: "docker-reactapp"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"