sudo: required 

services:
  - docker

before_install:
  - docker build -t dshah2012/docker-reactapp -f Dockerfile.dev .

script:
  - docker run dshah2012/docker-reactapp npm run test -- --coverage --watchAll=false